// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class PregledProfilaTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void pregledProfila() {
    driver.Navigate().GoToUrl("https://buybook.ba/");
    driver.Manage().Window.Size = new System.Drawing.Size(681, 703);
    driver.FindElement(By.CssSelector(".bi-person-circle")).Click();
    driver.FindElement(By.Id("email_1")).Click();
    driver.FindElement(By.Id("email_1")).SendKeys("test@test.com");
    driver.FindElement(By.Id("exampleInputPassword01")).Click();
    driver.FindElement(By.Id("exampleInputPassword01")).SendKeys("test1234!");
    driver.FindElement(By.Name("giris")).Click();
    driver.FindElement(By.CssSelector(".bi-person-circle")).Click();
    Assert.That(driver.Title, Is.EqualTo("Informacije o nalogu"));
    driver.FindElement(By.LinkText("Moje narudžbe")).Click();
    Assert.That(driver.Title, Is.EqualTo("Moje narudžbe"));
    driver.FindElement(By.LinkText("Moji favoriti")).Click();
    Assert.That(driver.Title, Is.EqualTo("Moji omiljeni predmeti"));
    Assert.That(driver.Title, Is.EqualTo("Moji omiljeni predmeti"));
    driver.FindElement(By.LinkText("Informacije o nalogu")).Click();
    Assert.That(driver.Title, Is.EqualTo("Informacije o nalogu"));
    Assert.That(driver.Title, Is.EqualTo("Informacije o nalogu"));
    driver.FindElement(By.LinkText("Odjava")).Click();
  }
}
